CREATE TABLE IF NOT EXISTS knowledge_document (
    id BIGINT NOT NULL AUTO_INCREMENT,
    filename VARCHAR(256) NOT NULL,
    document_id VARCHAR(64) NOT NULL,
    split_strategy VARCHAR(32) NOT NULL,
    department VARCHAR(128) NOT NULL,
    visible_role VARCHAR(128) NOT NULL,
    document_version VARCHAR(64) NOT NULL,
    content_type VARCHAR(32) NOT NULL,
    chunk_count INT UNSIGNED NOT NULL DEFAULT 0,
    average_token_count INT UNSIGNED NOT NULL DEFAULT 0,
    max_token_count INT UNSIGNED NOT NULL DEFAULT 0,
    overlap_token_count INT UNSIGNED NOT NULL DEFAULT 0,
    original_file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
    file_sha256 CHAR(64) NOT NULL,
    import_status VARCHAR(16) NOT NULL,
    last_error VARCHAR(1000) NULL,
    imported_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_knowledge_document_filename (filename),
    KEY idx_knowledge_document_document_id (document_id),
    KEY idx_knowledge_document_status (import_status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
