server:
  port: 8087

spring:
  application:
    name: mall-order-observability

observability:
  enabled: true
  service-name: mall-order-observability
  producer:
    enabled: false
  consumer:
    enabled: true
    group: rag-trace-consumer
  trace:
    topic: rag-trace-events
    tag: trace
  elasticsearch:
    uris: http://127.0.0.1:9200
    index: rag-traces

rocketmq:
  name-server: 127.0.0.1:9876
