
spring:
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: mall-order-cmp-server
        version: 0.0.1
        type: ASYNC  # Recommended for reactive applications
        # ?? sse ????????? /sse
        # ???????? ip:port/sse/mcp
        sse-endpoint: /sse
        sse-message-endpoint: /mcp
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        cors:
          allowed-origins: "*"
          allowed-methods: "*"
          allowed-headers: "*"
server:
  port: 8080
logging:
  level:
    io.modelcontextprotocol: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
